### ISSUE TITLE
Implement the pronouns

### ISSUE THREAD

**Issue by winkbrace** [wolfgang42/rockstar-js#4]
Please add supportfor the pronouns, which make the magic even better. :)

From the specification:

> Pronouns
> 
> The keywords it, he, she, him, her, them, they always refer to the most recently named variable, determined at parse time.

**Comment by wolfgang42** [comment]
Closed by c7aab0f3c466edb523decc84bc0cf5f6487002e5. I had this done yesterday and then fell asleep before I pushed. :smile:
