### ISSUE TITLE
All variables are global

### ISSUE THREAD

**Issue by JohnForster** [wolfgang42/rockstar-js#41]
Scope isn't preserved when defining variables.

```
SomeFunc takes my x
my y is 5
Give back my x with my y

Result is SomeFunc taking 6 (logs 11)
Shout Result

Shout my y (logs 5, should be undefined)
```

this should convert to 

```
function SomeFunc(myx) {
  var myy = "hello";
  return myx + myy;
}
var Result = SomeFunc(6);
console.log(Result);
console.log(myy);
```

but instead converts to

```
function SomeFunc(myx) {
  myy = "hello";
  return myx + myy;
}
Result = SomeFunc(6);
console.log(Result);
console.log(myy);
```

(on a side-note the keyword 'a' doesn't seem to be recognised, single letter variables eg. `X` and `Y` aren't recognised, and comments aren't preserved either)

**Comment by wolfgang42** [comment]
This looks at first glance like a legit bug, is there a reason you closed it?
